# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Edouard Fouché | Computer Science
email: edouard.fouche@hotmail.fr
description: A blog about computer science, art and culture
baseurl: "" # the subpath of your site, e.g. /blog

url: https://edouardfouche.com   # with the https protocol
enforce_ssl: edouardfouche.com   # without any protocol

twitter_username: edouardfouche
github_username:  edouardfouche

# Build settings
#markdown: kramdown
#highlighter: pygments
#markdown: kramdown

markdown: kramdown
kramdown:
  html_to_native: true
highlighter: rouge

#kramdown:
#  input: GFM
#  syntax_highlighter: rouge

  
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Your disqus shortname, entering this will enable commenting on posts
disqus: edouardfouche

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-56634264-1

# Other stuff
permalink: /:title/
# /blog/:year-:month-:day/:title.html

exclude: [README.md, LICENSE, Gemfile, Gemfile.lock]

# Feed
#feed:
#  path: feed.xml
#  limit: 20
#  #type: atom
